### ISSUE TITLE
Cannot share private domain

### ISSUE THREAD

**Issue by AlgorithmGoddess** [SAP-samples/btp-services-intelligent-routing#10]
Dear author,

I'm following your steps to build a HA test demo.

I'm now successfully mapped one CPI's API with custom domain service (as step-3), but when I configure the second one, I cannot map the second API with the same domain, even I have already run the command share-private-domain, could you please help to figure this issue out?

![image](https://user-images.githubusercontent.com/31646805/178199841-20a95f92-0a8b-47e0-84e2-bc3598bd41e5.png)

**Comment by MartinPankraz** [comment]
@maxstreifeneder and @hterminasyan,

there was a change in the process for the cf custom domain since I published the blog initially if I remember correctly, right?

@AlgorithmGoddess did you verify the general domain create process? Have a look at my outdated CLI sequence [here](https://blogs.sap.com/2021/01/18/second-round-of-crashing-iflows-in-cpi-and-failing-over-with-azure-even-simpler/). The wildcard domain is the same across both spaces, only the routes are different.

I suspect the domain sharing part changed, hence the issue. @maxstreifeneder and @hterminasyan will update my blog too once figured out how to clarify.

KR
Martin

**Comment by AlgorithmGoddess** [comment]
Hi All,

I have found my problem of this issue, it's because I was trying to create 2 map route in the same cloud foundry api endpoint. I then create another tenant with different area and can successfully do the routes and mapping.
Thanks all for help, especially thanks @MartinPankraz to ping me to help me out.
 
KR
Lexi
